### ISSUE TITLE
Frame_id in pose message should be odom instead of base_link

### ISSUE THREAD

**Issue by daniel-serrano** [srv/fovis#14]
Hi, 

Please correct me if I am wrong. If I understood correctly, 'odom_frame_id' is the world fixed frame, and 'base_link_frame_id'  is the moving frame attached to the camera/robot and the odom and pose messages describe the same pose in different manners. The odom message is  correctly publishing the pose of the child_frame_id (base_link) on the header.frame_id (odom).  But the pose message which describes the robot's current pose is refering to the base_link instead of the odom_frame. I believe the frame_id of this message should refer to the world fixed frame (odom). 

After changing line 123 in the file odometer_base.hpp from base_link_frame_id_ to odom_frame_id_ everything seems to work. Could you please confirm this or explain my mistake otherwise?

Thanks!
Daniel

**Comment by stwirth** [comment]
@daniel-serrano yes, you are right. Would you please open a pull-request to fix that? Thanks!

**Comment by daniel-serrano** [comment]
I have to learn how to do it but will do it later (sorry). Ignore my current pull request. I close it but don't know how to delete it.
