### ISSUE TITLE
x86 specific compile flags break on armhf builds

### ISSUE THREAD

**Issue by tfoote** [srv/fovis#17]
We're turning on arm builds and libfovis is failing due to manually setting flags. 

http://54.183.26.131:8080/job/Ibin_arm_uThf__libfovis__ubuntu_trusty_armhf__binary/171/console

```
[  4%] Building CXX object CMakeFiles/fovis.dir/libfovis/frame.cpp.o
/usr/lib/ccache/arm-linux-gnueabihf-g++   -Dfovis_EXPORTS -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -fPIC -I/usr/include/eigen3 -I/tmp/binarydeb/ros-indigo-libfovis-0.0.7/libfovis    -Wall -msse2 -msse3 -o CMakeFiles/fovis.dir/libfovis/frame.cpp.o -c /tmp/binarydeb/ros-indigo-libfovis-0.0.7/libfovis/frame.cpp
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-msse2’
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-msse3’
```

**Comment by miquelmassot** [comment]
Hi @tfoote! I think you put the issue in the wrong package. The compiling error is for libfovis, a package we also host. 
I'll check for SSE in cmake and depending on its availability, I'll add the corresponding definitions.

**Comment by miquelmassot** [comment]
And also https://github.com/srv/libfovis/commit/d3a53c2faaea86d1a9d9a20d6f8d954ffe89241b

**Comment by tfoote** [comment]
Thanks for the quick fix. Sorry about the wrong repo. I found this one via this wiki page: http://wiki.ros.org/libfovis clicking back to fuerte linked to this. You might consider adding a doc and devel entry in your rosdistro, and a few of the extra metadata in the package.xml and you'll get better wiki links automatically.
