### ISSUE TITLE
Catkinize and release for groovy

### ISSUE THREAD

**Issue by stwirth** [srv/fovis#2]
The package should be catkinized and released for groovy.
1. We should rename the branches:
   
   `master`->`fuerte`
   `develop`->`fuerte-devel`
2. Branch off new branches `groovy` and `groovy-devel`
3. Catkinize `groovy-devel` branch and merge to `groovy` when finished
4. Point default branch (HEAD) to `groovy`
5. Update rosdistro files for fuerte and groovy.

**Comment by stwirth** [comment]
The right way to use fovis would be to create a separate release package for the standalone fovis library using [bloom](http://www.ros.org/wiki/bloom/Tutorials/ReleaseThirdParty). Then it could be installed via `apt-get install ros-groovy-libfovis` and our package would contain only the ROS wrapper code.

**Comment by plnegre** [comment]
Standalone libfovis library was created (srv/libfovis-release@5ca8f7a5c805578af30997d9d187bc56f7456b0c) and the rosdistro build farm has been notified with this new package. Next I'll create the groovy version of fovis wrapper.

**Comment by stwirth** [comment]
Great! Where did you put the reference in rosdistro? I cannot find it.

**Comment by stwirth** [comment]
Just saw that your pull request is still pending (ros/rosdistro#666).

**Comment by stwirth** [comment]
You'll have to reorder the entry to be alphabetical, else it will not be accepted.

**Comment by plnegre** [comment]
Ooops, now corrected! (plnegre/rosdistro@8853b3ffb10c49cc26290ec0386d9b214d4db1ea)
