### ISSUE TITLE
problem in using fovis

### ISSUE THREAD

**Issue by neeba** [srv/fovis#5]
I tried to use fovis_ros with kinect But I got these msgs:

[ WARN] [1400569554.215914118]: The tf from '/base_link' to '/camera_rgb_optical_frame' does not seem to be available, will assume it as identity!

[ERROR] [1400569559.823182401]: fovis odometry failed: INSUFFICIENT_INLIERS

Thanks for attention

**Comment by miquelmassot** [comment]
Could you take a look at FovisInfo message and paste the output here?

**Comment by neeba** [comment]
I tried to subscribe FovisInfo message with rostopic echo but I got this err 

ERROR: Cannot load message class for [fovis_ros/FovisInfo]. Are your messages built?

**Comment by neeba** [comment]
I changed my Cmake but  I got the same errs:

[ERROR] [1400578137.105437418]: fovis odometry failed: NO_DATA
[ERROR] [1400578137.197044475]: fovis odometry failed: INSUFFICIENT_INLIERS
[ WARN] [1400578147.226398216]: The tf from '/base_link' to '/camera_rgb_optical_frame' does not seem to be available, will assume it as identity!

and when I tried to subscribe FovisInfo , I got the same err:

ERROR: Cannot load message class for [fovis_ros/FovisInfo]. Are your messages built?

**Comment by miquelmassot** [comment]
Ok. Can you please tell me which linux and ros distro are you using?

On 20 May 2014 10:32, neeba notifications@github.com wrote:

> I changed my Cmake but I got the same errs:
> 
> [ERROR] [1400578137.105437418]: fovis odometry failed: NO_DATA
> [ERROR] [1400578137.197044475]: fovis odometry failed: INSUFFICIENT_INLIERS
> [ WARN] [1400578147.226398216]: The tf from '/base_link' to
> '/camera_rgb_optical_frame' does not seem to be available, will assume it
> as identity!
> 
> and when I tried to subscribe FovisInfo the I got the same err:
> 
> ERROR: Cannot load message class for [fovis_ros/FovisInfo]. Are your
> messages built?
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/srv/fovis/issues/5#issuecomment-43604667
> .

## 

Miquel Massot

miquel.massot@gmail.com
http://www.facebook.com/massothttp://www.twitter.com/resisteixhttp://gplus.to/massot

**Comment by neeba** [comment]
I'm using ubuntu 13.04 and ros-hydro

**Comment by plnegre** [comment]
We didn't test fovis with ubuntu 13.04. In fact, ros-hydro only provide support for 12.04. However, it could work in your enviroment... We execute fovis with 12.04 and hydro.

Regarding to the errors: NO_DATA and INSUFFICIENT_INLIERS, it si common that they appear at the beginning of any execution. If they do not appear again means the odometry is being published.

The warning of the tf means that you have not set the transformation between /base_link and /camera_rgb_optical_frame. Set this using a static_transform_publisher, for example, and the warning will disappear.

**Comment by miquelmassot** [comment]
Closed for inactivity. If you still have issues, reopen this topic.
