### ISSUE TITLE
fovis hydro 

### ISSUE THREAD

**Issue by LiliMeng** [srv/fovis#9]
Hi,

```
    Thank you for contributing the fovis open source library! Currently I have some problem on fovis hydro version.

    First, I downloaded the hydro version package from ros wiki(http://wiki.ros.org/fovis_ros) by $git clone https://github.com/srv/fovis.git
    Then I used $catkin_make  under the catkin_ws directory.
    The following problems occurred: 
   CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
```

  Could not find a configuration file for package libfovis.

  Set libfovis_DIR to the directory containing a CMake configuration file for
  libfovis.  The file will have one of the following names:

```
libfovisConfig.cmake
libfovis-config.cmake

   Could anyone provide some suggestions? I am using Ubuntu12.04 , and ros hydro.

   Many thanks in advance! :) 
```

**Comment by miquelmassot** [comment]
Hi @LiliMeng,

you'll need to download ros-hydro-libfovis as well, as the error points out.

**Comment by LiliMeng** [comment]
Cool! Thanks a lot! That works good after I downloaded libfovis (https://github.com/srv/libfovis-release/tree/debian/hydro/precise/libfovis)! :)
